version: "3" 
services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./containers/mysql:/var/lib/mysql
  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - ./containers/redis:/data  
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      # REDIS_URL: "redis://redis:6379"
      DATABASE_URL: "mysql2://root:root@mysql:3306/dev"
    command: "bundle exec hanami server --host 0.0.0.0 -p 2300"
    volumes:
      - .:/app
      - ./containers/bundle_install:/app/vendor/bundle
      - ./containers/bundle:/app/.bundle
      - ./containers/node_modules:/app/node_modules
    ports:
      - "2300:2300"
    links:
      - mysql
      # - redis
