version: "3" 
services:
  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: development
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./containers/mysql:/var/lib/mysql
  adminer:
    image: adminer
    ports:
      - 8080:8080
    links:
      - mysql
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DATABASE_URL: mysql2://root:root@mysql:3306/development
    command: "bundle exec hanami server --host 0.0.0.0 -p 2300"
    volumes:
      - .:/app
      - ./containers/bundle_install:/app/vendor/bundle
      - ./containers/bundle:/app/.bundle
      - ./containers/node_modules:/app/node_modules
    ports:
      - 2300:2300
    links:
      - mysql
